"""Initial migration.

Revision ID: a338258f3e5c
Revises: 
Create Date: 2021-01-07 08:31:31.069147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a338258f3e5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Prerequiste',
    sa.Column('course_code', sa.String(length=5), nullable=False),
    sa.Column('pre_course_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['course.course_code'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pre_course_id'], ['course.course_code'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.drop_table('prerequiste')
    op.add_column('learns', sa.Column('course_code', sa.String(length=5), nullable=False))
    op.drop_constraint('learns_ibfk_2', 'learns', type_='foreignkey')
    op.create_foreign_key(None, 'learns', 'course', ['course_code'], ['course_code'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('learns', 'course_id')
    op.add_column('teaches', sa.Column('course_code', sa.String(length=5), nullable=False))
    op.drop_constraint('teaches_ibfk_2', 'teaches', type_='foreignkey')
    op.create_foreign_key(None, 'teaches', 'course', ['course_code'], ['course_code'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('teaches', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teaches', sa.Column('course_id', mysql.VARCHAR(length=5), nullable=False))
    op.drop_constraint(None, 'teaches', type_='foreignkey')
    op.create_foreign_key('teaches_ibfk_2', 'teaches', 'course', ['course_id'], ['course_code'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('teaches', 'course_code')
    op.add_column('learns', sa.Column('course_id', mysql.VARCHAR(length=5), nullable=False))
    op.drop_constraint(None, 'learns', type_='foreignkey')
    op.create_foreign_key('learns_ibfk_2', 'learns', 'course', ['course_id'], ['course_code'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('learns', 'course_code')
    op.create_table('prerequiste',
    sa.Column('course_id', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('pre_course_id', mysql.VARCHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_code'], name='prerequiste_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pre_course_id'], ['course.course_code'], name='prerequiste_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Prerequiste')
    # ### end Alembic commands ###
